tm_imu_node:
  ros__parameters:
    imu_baudrate : 115200
    imu_port : "/dev/transducerm"  # provided by udev rule (fallback to /dev/ttyACM0 if needed)
    imu_frame_id : 'imu'
    parent_frame_id : 'base_link'
    timer_period : 5
    transform : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
